[tokenizer]
n_vocab = 256
max_seq_length = 2048
max_words = 512
max_word_length = 32
pad_id = 0
end_id = 23
bos_id = 24

[word_encoder]
embedding_dim = 384
head_dim = 48
heads = 12
ff_mult = 12
depth = 4
local_attn_window_size = 96
use_dynamic_pos_bias = true
prenorm = false
attention_dropout = 0.0
ff_dropout = 0.0
