[train]
batch_size = 2
learning_rate = 1e-4
learning_rate_decay = 0.99998
epochs = 2
metrics_steps = 10

[data]
huggingface_id = "Trelis/tiny-shakespeare"
streaming = true
num_workers = 1
pin_memory = false
