[train]
batch_size = 2
learning_rate = 1e-4
learning_rate_decay = 0.99998
epochs = 2
metrics_steps = 10
checkpoint_steps = 1000
temperature = 0.1
contrastive = true
noise_probability = 0.5

[data]
huggingface_id = "Trelis/tiny-shakespeare"
#huggingface_id = "cerebras/SlimPajama-627B"
text_col = "Text"
streaming = true
num_workers = 1
pin_memory = false
